schedule_link_columns:
  - match_report
  - opponent
  - competition
  - round
schedule_rename_columns:
  comp: competition
  date: match_date
match_report_rename_columns:
  '#': shirtnumber
  pos: position
  min: minutes
  performance_gls: goals
  performance_ast: assists
  performance_pk: pk_goals
  performance_pkatt: pk_attempts
  performance_sh: shots
  performance_sot: shots_on_target
  performance_crdy: yellow_cards
  performance_crdr: red_cards
  performance_fouls: fouls
  performance_fld: fouled
  performance_off: offsides
  performance_tklw: tackles_won
  performance_int: interceptions
  performance_og: own_goals
  performance_pkwon: pks_won
  performance_pkcon: pks_converted
  performance_touches: touches
  performance_tkl: tackles
  performance_blocks: blocks
  expected_xg: xg
  expected_npxg: npxg
  expected_xag: xag
  sca_sca: shot_creating_actions
  sca_gca: goal_creating_actions
  passes_cmp: passes_completed
  passes_att: passes_attempted
  passes_cmp%: pass_completion_pct
  passes_prgp: progressive_passes
  carries_carries: carries
  carries_prgc: progressive_carries
  take-ons_att: take_ons_attempted
  take-ons_succ: take_ons_succeeded
match_report_dtypes:
  minutes: 'Int64'
  goals: 'Int64'
  assists: 'Int64'
  pk_goals: 'Int64'
  pk_attempts: 'Int64'
  shots: 'Int64'
  shots_on_target: 'Int64'
  yellow_cards: 'Int64'
  red_cards: 'Int64'
  fouls: 'Int64'
  fouled: 'Int64'
  offsides: 'Int64'
  tackles_won: 'Int64'
  interceptions: 'Int64'
  own_goals: 'Int64'
  pks_won: 'Int64'
  pks_converted: 'Int64'
  touches: 'Int64'
  tackles: 'Int64'
  blocks: 'Int64'
  xg: 'float'
  npxg: 'float'
  xag: 'float'
  shot_creating_actions: 'Int64'
  goal_creating_actions: 'Int64'
  passes_completed: 'Int64'
  passes_attempted: 'Int64'
  pass_completion_pct: 'float'
  progressive_passes: 'Int64'
  carries: 'Int64'
  progressive_carries: 'Int64'
  take_ons_attempted: 'Int64'
  take_ons_succeeded: 'Int64'
  shirtnumber: 'Int64'
roster_drop_columns:
  - club
  - age
  - player_link
  - mp
  - min
  - gls
roster_rename_columns:
  '#': 'wc_shirt_number'
  pos: 'wc_position'
  club_name: club
  age_years: age
competition_rename_columns:
  date: match_date
  date_links: match_date_link
  home: home_team
  away: away_team
  home_link: home_team_link
  away_link: away_team_link
  xg: home_xg
  xg.1: away_xg
competition_dtypes:
  home_xg: float
  away_xg: float
  home_goals: 'Int64'
  away_goals: 'Int64'
  attendance: 'Int64'
defense_rename_columns:
  tackles_tkl: tackles_att
  tackles_tklw: tackles_won
  tackles_def_3rd: tackles_def_third
  tackles_mid_3rd: tackles_mid_third
  tackles_att_3rd: tackles_att_third
  challenges_tkl: challenges_won
  blocks_blocks: blocks
  blocks_sh: shot_blocks
  blocks_pass: pass_blocks
  'int': interceptions
  clr: clearances
  err: errors_lead_to_shot
passing_rename_columns:
  total_cmp: passes_completed
  total_att: passes_attempted
  total_totdist: total_pass_distance
  total_prgdist: total_progressive_pass_distance
  short_cmp: short_passes_completed
  short_att: short_passes_attempted
  medium_cmp: medium_passes_completed
  medium_att: medium_passes_attempted
  long_cmp: long_passes_completed
  long_att: long_passes_attempted
  ast: assists
  kp: key_passes
  '1/3': passes_into_final_third
  ppa: passes_into_penalty_area
  crspa: crosses_into_penalty_area
  prgp: progressive_passes
possession_rename_columns:
  touches_touches: touches
  touches_def_pen: touches_def_penalty_area
  touches_def_3rd: touches_def_third
  touches_mid_3rd: touches_mid_third
  touches_att_3rd: touches_att_third
  touches_att_pen: touches_att_penalty_area
  take-ons_tkld: take_ons_tackled
  carries_totdist: total_carries_distance
  carries_prgdist: total_progressive_carries_distance
  carries_1/3: carries_into_final_third
  carries_cpa: carries_into_penalty_area
  carries_mis: carries_miscontrolled
  carries_dis: carries_disposessed
  receiving_rec: passes_recieved
  receiving_prgr: progressive_passes_recieved
misc_rename_columns:
  performance_2crdy: second_yellow_cards
  performance_fls: fouls
  performance_crs: crosses
  performance_int: interceptions
  performance_recov: ball_recoveries
passing_types_rename_columns:
  att: passes_attempted
  pass_types_live: passes_live
  pass_types_dead: passes_dead_ball
  pass_types_fk: passes_free_kick
  pass_types_tb: passes_through_balls
  pass_types_sw: passes_switches
  pass_types_ti: passes_throw_ins
  pass_types_ck: passes_corner_kicks
  corner_kicks_in: corner_kicks_inswinging
  corner_kicks_out: corner_kicks_outswinging
  corner_kicks_str: corner_kicks_straight
  outcomes_cmp: passes_completed
  outcomes_off: passes_offside
  outcomes_blocks: passes_blocked
shot_creation_rename_columns:
  player: shot_player
  player_link: shot_player_link
  'body part': body_part
